-- Migration: Tạo bảng parcels với đầy đủ trường theo yêu cầu
CREATE TABLE IF NOT EXISTS parcels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parcel_code TEXT,
    title TEXT,
    project_id TEXT,
    area REAL,
    person_in_charge TEXT,
    legal_status TEXT,
    clearance_status TEXT,
    parcel_color TEXT,
    description TEXT,
    land_use_purpose TEXT,
    owner TEXT,
    sheet_number TEXT,
    parcel_number TEXT,
    red_book_number TEXT,
    purchased_area REAL,
    outside_area REAL,
    field TEXT,
    full_address TEXT,
    hamlet TEXT,
    ward TEXT,
    province TEXT,
    expected_unit_price REAL,
    expected_total_price REAL,
    expected_broker_fee REAL,
    expected_notary_fee REAL,
    expected_total_cost REAL,
    transaction_status TEXT,
    purchased_area_actual REAL,
    outside_area_actual REAL,
    total_purchased_area REAL,
    transfer_doc_status TEXT,
    name_transfer_status TEXT,
    transferee TEXT,
    unit_price REAL,
    total_price REAL,
    deposit REAL,
    payment REAL,
    broker_fee REAL,
    notary_fee REAL,
    total_cost REAL,
    other_cost REAL,
    yield_bonus REAL,
    kpi_bonus REAL,
    total_bonus REAL,
    geometry TEXT,
    attachment TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
